-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 23:08:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controlfood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlfood` DEFAULT CHARACTER SET utf8 ;
USE `controlfood` ;

-- -----------------------------------------------------
-- Table `controlfood`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`usuarios` (
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data_de_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `acesso_criar_usuario` TINYINT NULL,
  `acesso_dashboard` TINYINT NULL,
  `acesso_criar_pedido` TINYINT NULL,
  `acesso_estoque` TINYINT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`ingrediente` (
  `Id_ingrediente` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  `contem_alergicos` TINYINT NULL,
  `informacoes_nutricionais` VARCHAR(255) NULL,
  PRIMARY KEY (`Id_ingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`historico_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`historico_entrada` (
  `id_historico` INT NOT NULL AUTO_INCREMENT,
  `data_entrada` DATETIME NULL,
  `quantidade` FLOAT NULL,
  `preco_pago` FLOAT NULL,
  `data_vencimento` DATE NULL,
  `marca` VARCHAR(45) NULL,
  `medida` VARCHAR(45) NULL,
  `ingrediente_Id_ingrediente` INT NOT NULL,
  PRIMARY KEY (`id_historico`, `ingrediente_Id_ingrediente`),
  INDEX `fk_historico_entrada_ingrediente1_idx` (`ingrediente_Id_ingrediente` ASC) VISIBLE,
  CONSTRAINT `fk_historico_entrada_ingrediente1`
    FOREIGN KEY (`ingrediente_Id_ingrediente`)
    REFERENCES `controlfood`.`ingrediente` (`Id_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`estoque` (
  `id_estoque` INT NOT NULL AUTO_INCREMENT,
  `quantidade` FLOAT NULL,
  `medida` VARCHAR(45) NULL,
  `quantidade_minima` FLOAT NULL,
  `ingrediente_Id_ingrediente` INT NOT NULL,
  PRIMARY KEY (`id_estoque`, `ingrediente_Id_ingrediente`),
  INDEX `fk_estoque_ingrediente1_idx` (`ingrediente_Id_ingrediente` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_ingrediente1`
    FOREIGN KEY (`ingrediente_Id_ingrediente`)
    REFERENCES `controlfood`.`ingrediente` (`Id_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`pratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`pratos` (
  `id_prato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL ,
  `descricao` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `tempo` INT NULL,
  PRIMARY KEY (`id_prato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`ingrediente_has_pratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`ingrediente_has_pratos` (
  `ingrediente_Id_ingrediente` INT NOT NULL,
  `pratos_id_prato` INT NOT NULL,
  `quantidade` FLOAT NULL,
  `medida` VARCHAR(45) NULL,
  PRIMARY KEY (`ingrediente_Id_ingrediente`, `pratos_id_prato`),
  INDEX `fk_ingrediente_has_pratos_pratos1_idx` (`pratos_id_prato` ASC) VISIBLE,
  INDEX `fk_ingrediente_has_pratos_ingrediente1_idx` (`ingrediente_Id_ingrediente` ASC) VISIBLE,
  CONSTRAINT `fk_ingrediente_has_pratos_ingrediente1`
    FOREIGN KEY (`ingrediente_Id_ingrediente`)
    REFERENCES `controlfood`.`ingrediente` (`Id_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingrediente_has_pratos_pratos1`
    FOREIGN KEY (`pratos_id_prato`)
    REFERENCES `controlfood`.`pratos` (`id_prato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`entregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`entregador` (
  `id_entregador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `telefone` VARCHAR(45) NULL,
  `veiculo` VARCHAR(45) NULL,
  `placa` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id_entregador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`entrega` (
  `id_entrega` INT NOT NULL AUTO_INCREMENT,
  `data_retirada` DATETIME NULL,
  `data_entrega` DATETIME NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`pedidos` (
  `cliente_id_cliente` INT NOT NULL,
  `entregador_id_entregador` INT NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` VARCHAR(45) NULL,
  `tempo_estimado` VARCHAR(45) NULL,
  `entrega_id_entrega` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `entregador_id_entregador`, `cliente_id_cliente`, `usuarios_id_usuario`, `entrega_id_entrega`),
  INDEX `fk_cliente_has_pratos_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_cliente_has_pratos_entregador1_idx` (`entregador_id_entregador` ASC) VISIBLE,
  INDEX `fk_cliente_has_pratos_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_pedidos_entrega1_idx` (`entrega_id_entrega` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_pratos_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `controlfood`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_pratos_entregador1`
    FOREIGN KEY (`entregador_id_entregador`)
    REFERENCES `controlfood`.`entregador` (`id_entregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_pratos_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `controlfood`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_entrega1`
    FOREIGN KEY (`entrega_id_entrega`)
    REFERENCES `controlfood`.`entrega` (`id_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlfood`.`pedidos_has_pratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlfood`.`pedidos_has_pratos` (
  `pedidos_id_pedido` INT NOT NULL,
  `pratos_id_prato` INT NOT NULL,
  PRIMARY KEY (`pedidos_id_pedido`, `pratos_id_prato`),
  INDEX `fk_pedidos_has_pratos_pratos1_idx` (`pratos_id_prato` ASC) VISIBLE,
  INDEX `fk_pedidos_has_pratos_pedidos1_idx` (`pedidos_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_pratos_pedidos1`
    FOREIGN KEY (`pedidos_id_pedido`)
    REFERENCES `controlfood`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_pratos_pratos1`
    FOREIGN KEY (`pratos_id_prato`)
    REFERENCES `controlfood`.`pratos` (`id_prato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `controlfood`.`pedidos_has_pratos` (
  `pedidos_id_pedido` INT NOT NULL,
  `pratos_id_prato` INT NOT NULL,
  PRIMARY KEY (`pedidos_id_pedido`, `pratos_id_prato`),
  INDEX `fk_pedidos_has_pratos_pratos1_idx` (`pratos_id_prato`),
  INDEX `fk_pedidos_has_pratos_pedidos1_idx` (`pedidos_id_pedido`),
  CONSTRAINT `fk_pedidos_has_pratos_pedidos1`
    FOREIGN KEY (`pedidos_id_pedido`)
    REFERENCES `controlfood`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_pratos_pratos1`
    FOREIGN KEY (`pratos_id_prato`)
    REFERENCES `controlfood`.`pratos` (`id_prato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;